version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - env/production.env
    volumes:
      # Mount the local "resources" folder so that container can access images
      - ./resources:/usr/src/app/resources
    depends_on:
      - mongo
    networks:
      - server-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - server-network

volumes:
  mongo_data:

networks:
  server-network: