version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - env/production.env
    volumes:
      # Mount the local "resources" folder so that container can access images
      - ./resources:/usr/src/app/resources
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: